"use client";
import {useState} from 'react';
import {Radio,Users,Hand,MicOff,Minimize2,MessageCircle,LogOut,ShieldCheck,CalendarDays} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Person={id:string;name:string;speaker:boolean;hand:boolean};
export default function LiveSession({name,date,onComments}:{name:string;date:number;onComments:()=>void}){
 const [open,setOpen]=useState(false),[started,setStarted]=useState(false),[joined,setJoined]=useState(false),[moderator,setModerator]=useState(false),[people,setPeople]=useState<Person[]>([]);
 const me=people.find(p=>p.id==='me');
 const patch=(id:string,value:Partial<Person>)=>setPeople(rows=>rows.map(p=>p.id===id?{...p,...value}:p));
 function start(){setStarted(true);setJoined(true);setPeople([{id:'me',name,speaker:true,hand:false}]);setOpen(true)}
 function join(){setJoined(true);setPeople(rows=>rows.some(p=>p.id==='me')?rows:[...rows,{id:'me',name,speaker:false,hand:false}]);setOpen(true)}
 function leave(){setJoined(false);setPeople(rows=>rows.filter(p=>p.id!=='me'));setOpen(false)}
 return <><section className="live-card"><div className="live-heading"><span className="live-icon"><Radio size={24}/></span><div><span className="eyebrow">HAFTALIK ONLAYN MUHOKAMA</span><h3>{started?'Suhbat interfeysi sinovi boshlandi':'Atom odatlar — birga tahlil qilamiz'}</h3></div></div><p className="session-date"><CalendarDays size={18}/>{date?new Date(date).toLocaleDateString('uz-UZ',{weekday:'long',day:'numeric',month:'long'}):'Yakshanba'} · 18:00 <small>qurilmangiz vaqti</small></p><p className="session-status">{started?`${people.length} ishtirokchi · lokal sinov`:'Moderator boshlagach qo‘shilish ochiladi.'}</p><button className="button" onClick={()=>started?joined?setOpen(true):join():setOpen(true)}>{started?joined?'Suhbat oynasiga qaytish':'Sinov xonasiga qo‘shilish':'Suhbat tafsilotlari'}</button></section>
 {started&&<div className="live-dock"><button onClick={()=>joined?setOpen(true):join()}><Radio size={22}/><span><strong>{joined?'Suhbat oynasiga qaytish':'Suhbatga qo‘shilish'}</strong><small>Atom odatlar · lokal sinov · {people.length} ishtirokchi</small></span></button>{joined&&<button aria-label="Suhbatdan chiqish" onClick={leave}><LogOut size={21}/></button>}</div>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="app-dialog live-dialog" showCloseButton={false}><div className="live-heading"><Radio size={25}/><DialogTitle>Atom odatlar</DialogTitle><button className="icon-btn" aria-label="Suhbat oynasini kichraytirish" onClick={()=>setOpen(false)}><Minimize2 size={20}/></button></div><DialogDescription>Haftalik ovozli muhokama</DialogDescription><p className="notice">Interfeys sinovi. Hozir ovoz uzatilmaydi, ishtirokchilar boshqa qurilmalarga sinxronlanmaydi. Haqiqiy suhbat xizmati hali ulanmagan.</p>
 {!started?<><p>Suhbatni moderator boshlaydi. Odamlar tinglovchi sifatida kiradi va gapirish uchun qo‘l ko‘taradi.</p><button className="button secondary" onClick={()=>setModerator(v=>!v)}><ShieldCheck size={18}/>{moderator?'Oddiy foydalanuvchi sinovi':'Moderator rolini sinash'}</button>{moderator&&<button className="button" onClick={start}>Sinov suhbatini boshlash</button>}</>:<><div className="section-row"><h3><Users size={18}/> Ishtirokchilar ({people.length})</h3><span>{moderator?'Moderator sinovi':'Tinglovchi sinovi'}</span></div><div className="participants">{people.map(p=><div className="participant" key={p.id}><span className="avatar">{p.name[0]}</span><div><strong>{p.id==='me'?name:p.name}{p.id==='me'?' (siz)':''}</strong><small>{p.speaker?'So‘zga ruxsat berilgan':'Tinglovchi'}{p.hand?' · qo‘l ko‘tardi':''}</small></div><MicOff size={18}/>{moderator&&p.id!=='me'&&<button className="text-btn" onClick={()=>patch(p.id,{speaker:!p.speaker,hand:false})}>{p.speaker?'Ruxsatni olish':'So‘z berish'}</button>}</div>)}</div>
 {joined&&!moderator&&<button className="button secondary" onClick={()=>patch('me',{hand:!me?.hand})}><Hand size={18}/>{me?.hand?'Qo‘lni tushirish':'So‘z so‘rash'}</button>}
 {moderator&&<><button className="button secondary" onClick={()=>setPeople(rows=>rows.some(p=>p.id==='demo')?rows:[...rows,{id:'demo',name:'Namunaviy tinglovchi',speaker:false,hand:true}])}>Namunaviy so‘z so‘rovini qo‘shish</button><button className="text-btn" onClick={()=>{setModerator(false);patch('me',{speaker:false})}}>Tinglovchi sifatida sinash</button></>}
 {!joined&&<button className="button" onClick={join}>Sinov xonasiga qo‘shilish</button>}
 <button className="button secondary" onClick={()=>{setOpen(false);onComments()}}><MessageCircle size={18}/>Suhbatni kichraytirib izoh yozish</button>
 {joined&&<button className="text-btn" onClick={leave}><LogOut size={18}/>Suhbatdan chiqish</button>}
 {moderator&&<button className="end-session" onClick={()=>{setStarted(false);setJoined(false);setPeople([]);setOpen(false)}}>Sinov suhbatini yakunlash</button>}</>}
 <button className="button secondary" onClick={()=>setOpen(false)}>Oynani yopish</button></DialogContent></Dialog></>
}
